var cookie = Cookies.get('lang');

WebApp.controller('committe-int', function($scope){
	
	$scope.Es = { 
		txt1: 'International Program Committee',
		txt2: 'Mark Cooper, Conference Deputy Chair, University of Queensland, Australia',
		txt3: 'Maria Otegui, University Buenos Aires, Argentina',
		txt4: 'Ruilian Jing, CAAS, China',
		txt5: 'Francois Tardieu, INRA, France',
		txt6: 'Rajeev Varshney, ICRISAT, India',
		txt7: 'Matthew Reynolds, CIMMYT, Mexico',
		txt8: 'Amelia Henry, IRRI, Philippines',
		txt9: 'Adam Price, University of Aberdeen, UK',
		txt10: 'Renee Lafitte, Bill and Melinda Gates Foundation, USA',
		txt11: '',
		txt12: '',
		txt13: '',
		txt14: '',
		txt15: '',
		txt16: '',
		txt17: '',
		txt18: '',
		txt19: '',
		txt20: '',
		txt21: '',
		txt22: '',
		txt23: '',
		txt24: '',
		txt25: '',
		txt26: '',
		txt27: '',
		txt28: '',
		txt29: '',
		txt30: '',
		txt31: '',
		txt32: '',
		txt33: '',
		txt34: '',
		txt35: '',
		txt36: '',
		txt37: '',
		txt38: '',
		txt39: '',
		txt40: '',
		txt41: '',
		txt42: '',
		txt43: '',
		txt44: '',
		txt45: '',
  }
  
  $scope.En = { 
	  	txt1: 'International Program Committee',
		txt2: 'Mark Cooper, Conference Deputy Chair, University of Queensland, Australia',
		txt3: 'Maria Otegui, University Buenos Aires, Argentina',
		txt4: 'Ruilian Jing, CAAS, China',
		txt5: 'Francois Tardieu, INRA, France',
		txt6: 'Rajeev Varshney, ICRISAT, India',
		txt7: 'Matthew Reynolds, CIMMYT, Mexico',
		txt8: 'Amelia Henry, IRRI, Philippines',
		txt9: 'Adam Price, University of Aberdeen, UK',
		txt10: 'Renee Lafitte, Bill and Melinda Gates Foundation, USA',
		txt11: '',
		txt12: '',
		txt13: '',
		txt14: '',
		txt15: '',
		txt16: '',
		txt17: '',
		txt18: '',
		txt19: '',
		txt20: '',
		txt21: '',
		txt22: '',
		txt23: '',
		txt24: '',
		txt25: '',
		txt26: '',
		txt27: '',
		txt28: '',
		txt29: '',
		txt30: '',
		txt31: '',
		txt32: '',
		txt33: '',
		txt34: '',
		txt35: '',
		txt36: '',
		txt37: '',
		txt38: '',
		txt39: '',
		txt40: '',
		txt41: '',
		txt42: '',
		txt43: '',
		txt44: '',
		txt45: '',
  }
	
	if(cookie == undefined || cookie === 'Es'){
		$scope.Lang = $scope.Es;
	} else {
		$scope.Lang = $scope.En;
	}
})// JavaScript Document// JavaScript Document