var cookie = Cookies.get('lang');

WebApp.controller('location', function($scope){
	
	$scope.Es = { 
		txt1: 'México',
		txt2: 'Catalogada por el New York Times como “la metrópoli que lo tiene todo” La Ciudad de México es ideal para perderse entre sus calles o para tener encuentros con el pasado histórico; ofrece rincones bohemios en bares y restaurantes tradicionales que se han vuelto un refugio para viajeros y locales.',
		txt3: 'Te trasporta a un mundo surrealista con la mixtura de la lucha libre, la majestuosidad del barroco, el lujo de sus palacios y su increíblemente variada vida nocturna donde encontrarás desde excéntricos lugares y típicas cantinas, hasta sitios que ofrecen una probada cosmopolita que es una muestra de las miles de culturas que convergen en esta ciudad. No es gratuito que este catalogada como una de las ciudades más divertidas para visitar.',
		txt4: 'La Ciudad de México es un destino con un misticismo extraordinario que se despliega en su pluralidad, su folclor y su modernidad; todo se mezcla con sus raíces prehispánicas presentes desde sus fundamentos, como lo muestra la Catedral metropolitana que en sus cimientos lleva la pirámide de Tonatiuh.',
		txt5: 'México se perfila como la 2da economía más grande de América Latina y la 11va más grande del mundo. Esto, aunado a su abundancia de atractivos naturales, su oferta cultural, una infraestructura especializada y su gama de actividades de ocio de primera categoría, ha resultado en el crecimiento rápido de la industria de Reuniones (convenciones, congresos, ferias y exposiciones).',
		txt6: 'Ciudad de México',
		txt7: 'La Ciudad de México es uno de los destinos más disfrutables del mundo. Su centro histórico, mejor conocido como Zócalo, es Patrimonio de la Humanidad declarado por la UNESCO y corazón de una cultura viva que exuda todo lo acumulado desde la fundación de Tenochtitlán. Visita sus barrios inundados del art nouveau y art déco, disfruta su oferta gastronómica y piérdete por las calles de la ciudad con más museos del mundo.',
		txt8: 'La gastronomía de la ciudad de México es tan prolífica y variada como su cultura misma. Se rejuvenece día con día, crece junto con sus habitantes. Además de los tacos y el guacamole, las quesadillas, los sopes,la famosa torta de chilaquiles, los esquites, las tortas, los dulces cristalizados que te esperan entre las calles, existen también diversas alternativas para vegetarianos y veganos.',
		txt9: 'también diversas alternativas para vegetarianos y veganos. Si lo que buscas es la elegancia, encontrarás restaurantes catalogados dentro de los 50 mejores del mundo que te envolverán en una atmósfera de sabor, lujos y majestuosidad.',
		txt10: 'Información sobre CIMMYT y la Semana de Visitantes de Trigo de Obregón',
		txt11: 'El Centro Internacional de Mejoramiento de Maíz y Trigo (CIMMYT) es líder mundial en investigación de maíz, trigo y sistemas agrícolas relacionados. Con sede cerca de la Ciudad de México, el CIMMYT trabaja con cientos de socios y colaboradores en todo el mundo en desarrollo para aumentar de manera sostenible la productividad de los sistemas de cultivo de maíz y trigo, mejorando así la seguridad alimentaria global y reduciendo la pobreza. El CIMMYT es miembro del Sistema CGIAR y dirige los Programas de Investigación del CGIAR sobre Maíz y Trigo y la Plataforma de Excelencia en Mejoramiento. El Centro cuenta con el apoyo de gobiernos nacionales, fundaciones, bancos de desarrollo y otros organismos públicos y privados.',
		txt12: 'La sede del CIMMYT es un destino muy solicitado por visitantes que alberga cada año a cientos de estudiantes, científicos, líderes internacionales y funcionarios gubernamentales de todo el mundo. En el CIMMYT, los visitantes pueden explorar nuestras modernas instalaciones de investigación científica y mejoramiento, la estación experimental de 87 hectáreas de extensión, el museo del CIMMYT y el reconocido centro de recursos fitogenéticos, donde se encuentra la bóveda de nuestro banco de germoplasma e información general del Centro.',
		txt13: 'ACERCA DE LA ESTACIÓN EXPERIMENTAL NORMAN E. BORLAUG',
		txt14: '(Campo Experimental Norman E. Borlaug, CENEB)',
		txt15: 'Ciudad Obregón, Estado de Sonora',
		txt16: 'Al norte del país, en Obregón, estado de Sonora, sobre una extensión de 240 hectáreas, se encuentra la estación experimental más grande y antigua del CIMMYT. Esta estación se estableció en 1930 y, en 1945, fue sede del programa de mejoramiento alternado de trigo del Dr. Borlaug, el cual se llevó a cabo entre la ciudad de Obregón y la Ciudad de México. En 1960, el Dr. Borlaug y su equipo crearon el primer trigo semi-enano de alto rendimiento y resistente a enfermedades – un éxito que posteriormente conduciría a la Revolución Verde. Hoy en día, las instalaciones en Obregón son utilizadas principalmente por el Programa Global de Trigo del CIMMYT como una estación de mejoramiento y centro de capacitación durante el verano. Debido a su clima cálido y seco, la estación es ideal para encontrar un mayor potencial de rendimiento, tolerancia al calor y la sequía, y resiliencia a enfermedades y plagas importantes para ofrecer variedades más productivas a los pequeños agricultores. La estación también es un centro de avances de fenotipado y despliegue de tecnología.',
		txt17: '',
		txt18: '',
		txt19: '',
		txt20: '',
		txt21: '',
		txt22: '',
		txt23: '',
		txt24: '',
		txt25: '',
		txt26: '',
		txt27: '',
		txt28: '',
		txt29: '',
		txt30: '',
		txt31: '',
		txt32: '',
		txt33: '',
		txt34: '',
		txt35: '',
		txt36: '',
		txt37: '',
		txt38: '',
		txt39: '',
		txt40: '',
		txt41: '',
		txt42: '',
		txt43: '',
		txt44: '',
		txt45: '',
  }
  
  $scope.En = { 
		txt1: 'México',
		txt2: 'Named as "the metropolis that has it all" by the New York Times, Mexico City allows you to penetrate its streets and encounter their historical past; it offers bohemian corners nestled in traditional bars and restaurants that have become a haven for travelers and locals alike.',
		txt3: 'It transports you to a surreal world comprised of the eclectic mix of wrestling matches, grand baroque aesthetic, and luxurious palaces. It has an incredibly diverse nightlife, where you will find everything from unconventional clubs to typical canteens, and venues that offer a cosmopolitan flavor, which represents but a fragment of the complex cultural mosaic that converges in this city. It comes as no surprise that it is considered one of the most exciting cities to visit.',
		txt4: 'Mexico City is a destination with an extraordinary mysticism that revels in its overlapping plurality, folklore, and modernity; everything here is an intermixture, its pre-Hispanic roots present in its foundations, as shown by the Metropolitan Cathedral that sits on top of the pyramid of Tonatiuh.',
		txt5: 'Mexico is emerging as the 2nd largest economy in Latin America and the 11th largest in the world. This, coupled with its abundance of natural attractions, its cultural offerings, a specialized infrastructure and its range of top-notch leisure activities, has resulted in the rapid growth of the Meetings industry (conventions, congresses, fairs and exhibitions).',
		txt6: 'Mexico City',
		txt7: 'Mexico City is one of the most enjoyable destinations. Its historic center, better known as Zocalo, is declared World Heritage by UNESCO and is the heart of a living culture that exudes everything accumulated since the founding of Tenochtitlan. Visit its neighborhoods flooded with art nouveau and art deco, enjoy its cuisine and lose yourself in the streets of the city with the most museums in the world.',
		txt8: 'The cuisine of Mexico City is as prolific and varied as its culture itself. It rejuvenates day by day, grows along with its inhabitants. In addition to the tacos and guacamole, the quesadillas, the sopes, the famous chilaquiles cake, the esquites, the cakes, the crystallized sweets that await you in the streets, there are also various alternatives for vegetarians and vegans.',
		txt9: 'If you´re looking for elegance, you´ll find restaurants cataloged among the 50 best in the world that will wrap you in an atmosphere of taste, luxury and majesty.',
		txt10: 'Info about CIMMYT & Obregon Wheat Visitor Week',
		txt11: 'CIMMYT – the International Maize and Wheat Improvement Center – is the global leader in publicly funded maize and wheat research and related farming systems. Headquartered near Mexico City, CIMMYT works with hundreds of partners throughout the developing world to sustainably increase the productivity of maize and wheat cropping systems, thus improving global food security and reducing poverty. CIMMYT is a member of the CGIAR System and leads the CGIAR Research Programs on Maize and Wheat and the Excellence in Breeding Platform. The Center receives support from national governments, foundations, development banks and other public and private agencies.',
		txt12: 'CIMMYT headquarters is a much sought visitor destination, and is host each year to hundreds of students, scientists, international leaders and government officials from around the world. At CIMMYT, visitors can explore our state-of-the-art scientific research and breeding facilities, the 87-hectare experiment station, the CIMMYT museum, and the renowned plant genetic resources center that features our gene bank vaults and information center.',
		txt13: 'ABOUT THE NORMAN E. BORLAUG EXPERIMENT STATION',
		txt14: '(Campo Experimental Norman E. Borlaug, CENEB)',
		txt15: 'Ciudad Obregón, State of Sonora',
		txt16: 'In the northern state of Sonora, in the city of Obregon – over an expansive 240 hectares – lies CIMMYT’s largest and oldest experiment station. This station was established in 1930, and by 1945, was host to Dr. Borlaug’s wheat “shuttle breeding” program between Obregon and Mexico City. By 1960, Dr. Borlaug and his team had created the first high-yielding semi-dwarf, disease resistant wheat – a success that soon would lead to the Green Revolution. Today, the facilities at Obregon are used primarily by CIMMYT’s Global Wheat Program as a summer breeding station and training center. Due to its hot and dry climate, the station is ideal for pursuing enhanced yield potential, tolerance to heat and drought, and resistance to major diseases and pests to deliver more productive varieties to smallholder farmers. The station is also a center of phenotyping advances and technology deployment.',
		txt17: '',
		txt18: '',
		txt19: '',
		txt20: '',
		txt21: '',
		txt22: '',
		txt23: '',
		txt24: '',
		txt25: '',
		txt26: '',
		txt27: '',
		txt28: '',
		txt29: '',
		txt30: '',
		txt31: '',
		txt32: '',
		txt33: '',
		txt34: '',
		txt35: '',
		txt36: '',
		txt37: '',
		txt38: '',
		txt39: '',
		txt40: '',
		txt41: '',
		txt42: '',
		txt43: '',
		txt44: '',
		txt45: '',
  }
	
	if(cookie == undefined || cookie === 'Es'){
		$scope.Lang = $scope.Es;
	} else {
		$scope.Lang = $scope.En;
	}
})  // JavaScript Document// JavaScript Document