var cookie = Cookies.get('lang');

WebApp.controller('program', function($scope){
	
	$scope.Es = { 
		txt1: '',
		txt2: '',
		txt3: '',
		txt4: '',
		txt5: '',
		txt6: '',
		txt7: '',
		txt8: '',
		txt9: '',
		txt10: '',
		txt11: '',
		txt12: '',
		txt13: '',
		txt14: '',
		txt15: '',
		txt16: '',
		txt17: '',
		txt18: '',
		txt19: '',
		txt20: '',
		txt21: '',
		txt22: '',
		txt23: '',
		txt24: '',
		txt25: '',
		txt26: '',
		txt27: '',
		txt28: '',
		txt29: '',
		txt30: '',
		txt31: '',
		txt32: '',
		txt33: '',
		txt34: '',
		txt35: '',
		txt36: '',
		txt37: '',
		txt38: '',
		txt39: '',
		txt40: '',
		txt41: '',
		txt42: '',
		txt43: 'PROGRAMA',
		txt44: '',
		txt45: '',
  }
  
  $scope.En = { 
		txt1: 'Monday 9 March',
		txt2: 'Registration',
		txt3: 'Session 1: Opening of InterDrought VI',
		txt4: 'Tea/Coffee Break',
		txt5: 'Session 2: Optimising dryland crop production – crop design',
		txt6: 'Lunch',
		txt7: 'Symposia: 4 parallel symposium sessions',
		txt8: 'Tea/Coffee Break',
		txt9: 'Poster Session',
		txt10: 'Welcome cocktail event',
		txt11: 'Tuesday 10 March',
		txt12: 'Wednesday 11 March',
		txt13: 'Session 3: Plant productivity under drought: Water capture, transpiration, and transpiration efficiency',
		txt14: 'Tea/Coffee Break',
		txt15: 'Session 4: Plant productivity under drought: Vegetative and reproductive growth',
		txt16: 'Lunch',
		txt17: 'Symposia: 4 parallel symposium sessions',
		txt18: 'Tea/Coffee Break',
		txt19: 'Poster Session',
		txt20: 'Free',
		txt21: 'Session 5: Breeding for water-limited environments',
		txt22: 'Session 6: Managing cropping systems for adaptation to water-limited environments',
		txt23: 'Session 7 – Future perspectives',
		txt24: 'Concluding remarks',
		txt25: 'Conference Dinner',
		txt26: 'Friday 13 March: Day trip to CIMMYT and Teothiuacan pyramids',
		txt27: 'Buses depart to CIMMYT',
		txt28: 'Welcome; Divide up in eight groups',
		txt29: 'Interactive Sessions 1 & 2',
		txt30: 'Interactive Sessions 3 & 4',
		txt31: 'Traditional Mexican Barbeque',
		txt32: 'Transfer to Teothiuacan, with some of the most significant Mesoamerican pyramids built in the pre-Columbian era',
		txt33: 'Visit of Teothiuacan; visitors pay an entry fee of 75 Mexican pesos',
		txt34: 'Return to Mexico City',
		txt35: 'Visit to CIMMYT: All groups will be able to visit four sessions',
		txt36: 'A1 & A2:  Finding stress tolerance in the germplasm bank',
		txt37: 'B1 & B2:  Stress phenotyping in applied breeding programs',
		txt38: 'C1 & C2:  Crop management',
		txt39: 'D1 & D2:  Reaching farmers',
		txt40: 'Post Conference Activity',
		txt41: 'Second part of March is an ideal time to visit CIMMYT’s wheat breeding and research activities at the world’s largest public wheat breeding station in Obregon, in the North of Mexico. For more information click ',
		txt42: 'Thursday 12 March',
		txt43: 'PROGRAM',
		txt44: 'here.',
		txt45: '',
  }
	
	if(cookie == undefined || cookie === 'Es'){
		$scope.Lang = $scope.Es;
	} else {
		$scope.Lang = $scope.En;
	}
})  // JavaScript Document