var cookie = Cookies.get('lang');

WebApp.controller('welcome', function($scope){
	
	$scope.Es = { 
		txt1: 'Bienvenida',
		txt2: '',
		txt3: '',
		txt4: '',
		txt5: '',
		txt6: '',
		txt7: '',
		txt8: '',
		txt9: '',
		txt10: '',
		txt11: '',
		txt12: '',
		txt13: '',
		txt14: '',
		txt15: '',
		txt16: '',
		txt17: '',
		txt18: '',
		txt19: '',
		txt20: '',
		txt21: '',
		txt22: '',
		txt23: '',
		txt24: '',
		txt25: '',
		txt26: '',
		txt27: '',
		txt28: '',
		txt29: '',
		txt30: '',
		txt31: '',
		txt32: '',
		txt33: '',
		txt34: '',
		txt35: '',
		txt36: '',
		txt37: '',
		txt38: '',
		txt39: '',
		txt40: '',
		txt41: '',
		txt42: '',
		txt43: '',
		txt44: '',
		txt45: '',
  }
  
  $scope.En = { 
		txt1: 'Dear Colleagues,',
		txt2: 'Invitation to join us at INTERDROUGHT VI in Mexico City, 9-13 March 2020',
		txt3: 'We are pleased to invite you to participate in the 6 th International INTERDROUGHT Symposium.',
		txt4: 'INTERDROUGHT VI (IDVI) aims to facilitate the development of concepts, methods and technologiesnassociated with plant production in water-limited environments, with the objective of in-depth exchange of scientific ideas and experience across disciplines and countries. IDVI follows on from the successful series of congresses that have gathered scientists involved in this domain (Montpellier 1995, Rome 2005, Shanghai 2009, Perth 2013, Hyderabad, 2017). IDVI will continue the philosophy of presenting, discussing and integrating results of both applied and basic research towards the development of solutions for improving crop production under drought-prone conditions. IDVI will serve as a platform for presenting and debating key issues and strategies relevant for increasing the yield and stability of crops under water-limited conditions by genetic and crop management approaches. IDVI provides an essential forum for cross-talk among scientists operating in this research area at crop, whole plant, and molecular levels.',
		txt5: 'IDVI will focus on a range of topics including –',
		txt6: 'Optimising dryland crop production – crop design',
		txt7: 'Plant productivity under drought I - Water capture, transpiration, transpiration efficiency',
		txt8: 'Plant productivity under drought II – Vegetative and reproductive growth',
		txt9: 'Breeding for water-limited environments',
		txt10: 'Managing cropping systems for adaptation to water-limited environments',
		txt11: 'INTERDROUGHT VI is very timely in view of the impending global food deficit, the associated need to enhance the rate of increase in crop productivity, and the exacerbating of these issues by global climate change, which often involves increased water scarcity. Farmers are seeking solutions for sustaining livelihood under these circumstances in both developing and developed countries.',
		txt12: 'We are making every effort to create a memorable and enjoyable meeting for you at IDVI.',
		txt13: 'We look forward to seeing you in Mexico City.',
		txt14: 'On behalf of the International Program Committee, Organising Committee, and INTERDROUGHT Assembly',
		txt15: 'Graeme Hammer',
		txt16: 'IDVI Conference Chair',
		txt17: 'Professor in Crop Science',
		txt18: 'The University of Queensland',
		txt19: 'Brisbane, Qld, Australia',
		txt20: '',
		txt21: '',
		txt22: '',
		txt23: '',
		txt24: '',
		txt25: '',
		txt26: '',
		txt27: '',
		txt28: '',
		txt29: '',
		txt30: '',
		txt31: '',
		txt32: '',
		txt33: '',
		txt34: '',
		txt35: '',
		txt36: '',
		txt37: '',
		txt38: '',
		txt39: '',
		txt40: '',
		txt41: '',
		txt42: '',
		txt43: '',
		txt44: '',
		txt45: '',
  }
	
	if(cookie == undefined || cookie === 'Es'){
		$scope.Lang = $scope.Es;
	} else {
		$scope.Lang = $scope.En;
	}
})  // JavaScript Document